<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataMobilSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('data_mobil')->insert([
                        ['id' => 1, 'merk' => 'Toyota', 'model' => 'Avanza'],
            ['id' => 2, 'merk' => 'Toyota', 'model' => 'Innova'],
            ['id' => 3, 'merk' => 'Toyota', 'model' => 'Fortuner'],
            ['id' => 4, 'merk' => 'Toyota', 'model' => 'Yaris'],
            ['id' => 15, 'merk' => 'Toyota', 'model' => 'Kijang'],
            ['id' => 16, 'merk' => 'Toyota', 'model' => 'Veloz'],
            ['id' => 17, 'merk' => 'Toyota', 'model' => 'Calya'],
            ['id' => 18, 'merk' => 'Toyota', 'model' => 'Agya'],
            ['id' => 19, 'merk' => 'Toyota', 'model' => 'Yaris Cross'],
            ['id' => 20, 'merk' => 'Toyota', 'model' => 'Vios'],
            ['id' => 21, 'merk' => 'Toyota', 'model' => 'Corolla Altis'],
            ['id' => 22, 'merk' => 'Toyota', 'model' => 'Camry'],
            ['id' => 23, 'merk' => 'Toyota', 'model' => 'Corolla Cross'],
            ['id' => 24, 'merk' => 'Toyota', 'model' => 'Rush'],
            ['id' => 25, 'merk' => 'Toyota', 'model' => 'Raize'],
            ['id' => 26, 'merk' => 'Toyota', 'model' => 'Hilux'],
            ['id' => 27, 'merk' => 'Toyota', 'model' => 'Alphard'],
            ['id' => 28, 'merk' => 'Toyota', 'model' => 'Vellfire'],
            ['id' => 29, 'merk' => 'Toyota', 'model' => 'Land Cruiser'],
            ['id' => 30, 'merk' => 'Toyota', 'model' => 'Land Cruiser Prado'],
            ['id' => 31, 'merk' => 'Toyota', 'model' => 'Sienta'],
            ['id' => 32, 'merk' => 'Toyota', 'model' => 'Etios Valco'],
            ['id' => 33, 'merk' => 'Toyota', 'model' => 'Etios Sedan'],
            ['id' => 34, 'merk' => 'Toyota', 'model' => 'Dyna'],
            ['id' => 35, 'merk' => 'Toyota', 'model' => 'HiAce'],
            ['id' => 36, 'merk' => 'Toyota', 'model' => 'Dyna Truck'],
            ['id' => 37, 'merk' => 'Toyota', 'model' => 'Hilux Single Cabin'],
            ['id' => 38, 'merk' => 'Toyota', 'model' => 'Hilux Double Cabin'],
            ['id' => 39, 'merk' => 'Toyota', 'model' => 'Rush TRD Sportivo'],
            ['id' => 40, 'merk' => 'Toyota', 'model' => 'Agya GR Sport'],
            ['id' => 41, 'merk' => 'Toyota', 'model' => 'Yaris GR Sport'],
            ['id' => 42, 'merk' => 'Toyota', 'model' => 'Vios GR Sport'],
            ['id' => 43, 'merk' => 'Toyota', 'model' => 'Camry Hybrid'],
            ['id' => 44, 'merk' => 'Toyota', 'model' => 'Corolla Altis Hybrid'],
            ['id' => 45, 'merk' => 'Toyota', 'model' => 'Alphard Hybrid'],
            ['id' => 46, 'merk' => 'Toyota', 'model' => 'Vellfire Hybrid'],
            ['id' => 47, 'merk' => 'Toyota', 'model' => 'Innova Venturer'],
            ['id' => 48, 'merk' => 'Toyota', 'model' => 'Kijang Super'],
            ['id' => 49, 'merk' => 'Toyota', 'model' => 'Soluna'],
            ['id' => 50, 'merk' => 'Toyota', 'model' => 'Starlet'],

            ['id' => 51, 'merk' => 'Daihatsu', 'model' => 'Xenia'],
            ['id' => 52, 'merk' => 'Daihatsu', 'model' => 'Terios'],
            ['id' => 53, 'merk' => 'Daihatsu', 'model' => 'Ayla'],
            ['id' => 54, 'merk' => 'Daihatsu', 'model' => 'Sigra'],
            ['id' => 55, 'merk' => 'Daihatsu', 'model' => 'Sirion'],
            ['id' => 56, 'merk' => 'Daihatsu', 'model' => 'Gran Max Minibus'],
            ['id' => 57, 'merk' => 'Daihatsu', 'model' => 'Gran Max Pickup'],
            ['id' => 58, 'merk' => 'Daihatsu', 'model' => 'Luxio'],
            ['id' => 59, 'merk' => 'Daihatsu', 'model' => 'Espass'],
            ['id' => 60, 'merk' => 'Daihatsu', 'model' => 'Zebra'],
            ['id' => 61, 'merk' => 'Daihatsu', 'model' => 'Ceria'],
            ['id' => 62, 'merk' => 'Daihatsu', 'model' => 'Taruna'],
            ['id' => 63, 'merk' => 'Daihatsu', 'model' => 'Himax'],
            ['id' => 64, 'merk' => 'Daihatsu', 'model' => 'Rocky'],
            ['id' => 65, 'merk' => 'Daihatsu', 'model' => 'Hi-Max'],
            ['id' => 66, 'merk' => 'Daihatsu', 'model' => 'Taft (F70/F75)'],
            ['id' => 67, 'merk' => 'Daihatsu', 'model' => 'Taft GT'],
            ['id' => 68, 'merk' => 'Daihatsu', 'model' => 'Taft Hiline'],
            ['id' => 69, 'merk' => 'Daihatsu', 'model' => 'Charade'],
            ['id' => 70, 'merk' => 'Daihatsu', 'model' => 'Charade Classy'],
            ['id' => 71, 'merk' => 'Daihatsu', 'model' => 'Feroza'],
            ['id' => 72, 'merk' => 'Daihatsu', 'model' => 'Hiline Pickup'],

            ['id' => 73, 'merk' => 'Honda', 'model' => 'Brio'],
            ['id' => 74, 'merk' => 'Honda', 'model' => 'Jazz'],
            ['id' => 75, 'merk' => 'Honda', 'model' => 'City'],
            ['id' => 76, 'merk' => 'Honda', 'model' => 'City Hatchback'],
            ['id' => 77, 'merk' => 'Honda', 'model' => 'Civic'],
            ['id' => 78, 'merk' => 'Honda', 'model' => 'Accord'],
            ['id' => 79, 'merk' => 'Honda', 'model' => 'CR-V'],
            ['id' => 80, 'merk' => 'Honda', 'model' => 'HR-V'],
            ['id' => 81, 'merk' => 'Honda', 'model' => 'BR-V'],
            ['id' => 82, 'merk' => 'Honda', 'model' => 'Mobilio'],
            ['id' => 83, 'merk' => 'Honda', 'model' => 'Odyssey'],
            ['id' => 84, 'merk' => 'Honda', 'model' => 'Freed'],
            ['id' => 85, 'merk' => 'Honda', 'model' => 'Stream'],
            ['id' => 86, 'merk' => 'Honda', 'model' => 'Pilot'],
            ['id' => 87, 'merk' => 'Honda', 'model' => 'CR-Z'],
            ['id' => 88, 'merk' => 'Honda', 'model' => 'Insight'],

            ['id' => 89, 'merk' => 'Mitsubishi', 'model' => 'Xpander'],
            ['id' => 90, 'merk' => 'Mitsubishi', 'model' => 'Xpander Cross'],
            ['id' => 91, 'merk' => 'Mitsubishi', 'model' => 'Pajero Sport'],
            ['id' => 92, 'merk' => 'Mitsubishi', 'model' => 'Pajero'],
            ['id' => 93, 'merk' => 'Mitsubishi', 'model' => 'Outlander Sport'],
            ['id' => 94, 'merk' => 'Mitsubishi', 'model' => 'Outlander'],
            ['id' => 95, 'merk' => 'Mitsubishi', 'model' => 'L300'],
            ['id' => 96, 'merk' => 'Mitsubishi', 'model' => 'Colt T120SS'],
            ['id' => 97, 'merk' => 'Mitsubishi', 'model' => 'Colt Diesel FE Series'],
            ['id' => 98, 'merk' => 'Mitsubishi', 'model' => 'Triton'],
            ['id' => 99, 'merk' => 'Mitsubishi', 'model' => 'Strada Triton'],
            ['id' => 100, 'merk' => 'Mitsubishi', 'model' => 'Delica'],
             ['id' => 101, 'merk' => 'Mitsubishi', 'model' => 'Grandis'],
    ['id' => 102, 'merk' => 'Mitsubishi', 'model' => 'Mirage'],
    ['id' => 103, 'merk' => 'Mitsubishi', 'model' => 'Eclipse Cross'],
    ['id' => 104, 'merk' => 'Suzuki', 'model' => 'Ertiga'],
    ['id' => 105, 'merk' => 'Suzuki', 'model' => 'XL7'],
    ['id' => 106, 'merk' => 'Suzuki', 'model' => 'Swift'],
    ['id' => 107, 'merk' => 'Suzuki', 'model' => 'Baleno'],
    ['id' => 108, 'merk' => 'Suzuki', 'model' => 'Ignis'],
    ['id' => 109, 'merk' => 'Suzuki', 'model' => 'Karimun Wagon R'],
    ['id' => 110, 'merk' => 'Suzuki', 'model' => 'Karimun Estilo'],
    ['id' => 111, 'merk' => 'Suzuki', 'model' => 'APV Arena'],
    ['id' => 112, 'merk' => 'Suzuki', 'model' => 'Jimny'],
    ['id' => 113, 'merk' => 'Suzuki', 'model' => 'SX4 S-Cross'],
    ['id' => 114, 'merk' => 'Suzuki', 'model' => 'Grand Vitara'],
    ['id' => 115, 'merk' => 'Nissan', 'model' => 'X-Trail'],
    ['id' => 116, 'merk' => 'Nissan', 'model' => 'Livina'],
    ['id' => 117, 'merk' => 'Nissan', 'model' => 'Grand Livina'],
    ['id' => 118, 'merk' => 'Nissan', 'model' => 'Serena'],
    ['id' => 119, 'merk' => 'Nissan', 'model' => 'Juke'],
    ['id' => 120, 'merk' => 'Nissan', 'model' => 'Terra'],
    ['id' => 121, 'merk' => 'Nissan', 'model' => 'March'],
    ['id' => 122, 'merk' => 'Nissan', 'model' => 'Evalia'],
    ['id' => 123, 'merk' => 'Nissan', 'model' => 'Teana'],
    ['id' => 124, 'merk' => 'Nissan', 'model' => 'Navara'],
    ['id' => 125, 'merk' => 'Mazda', 'model' => 'Mazda2'],
    ['id' => 126, 'merk' => 'Mazda', 'model' => 'Mazda3'],
    ['id' => 127, 'merk' => 'Mazda', 'model' => 'Mazda6'],
    ['id' => 128, 'merk' => 'Mazda', 'model' => 'CX-3'],
    ['id' => 129, 'merk' => 'Mazda', 'model' => 'CX-30'],
    ['id' => 130, 'merk' => 'Mazda', 'model' => 'CX-5'],
    ['id' => 131, 'merk' => 'Mazda', 'model' => 'CX-9'],
    ['id' => 132, 'merk' => 'Mazda', 'model' => 'BT-50'],
    ['id' => 133, 'merk' => 'Mazda', 'model' => 'Biante'],
    ['id' => 134, 'merk' => 'Mazda', 'model' => 'CX-7'],
    ['id' => 135, 'merk' => 'Lexus', 'model' => 'RX'],
    ['id' => 136, 'merk' => 'Lexus', 'model' => 'NX'],
    ['id' => 137, 'merk' => 'Lexus', 'model' => 'UX'],
    ['id' => 138, 'merk' => 'Lexus', 'model' => 'LX'],
    ['id' => 139, 'merk' => 'Lexus', 'model' => 'GX'],
    ['id' => 140, 'merk' => 'Lexus', 'model' => 'ES'],
    ['id' => 141, 'merk' => 'Lexus', 'model' => 'LS'],
    ['id' => 142, 'merk' => 'Lexus', 'model' => 'IS'],
    ['id' => 143, 'merk' => 'Mitsubishi', 'model' => 'Xpander'],
    ['id' => 144, 'merk' => 'Mitsubishi', 'model' => 'Xpander Cross'],
    ['id' => 145, 'merk' => 'Mitsubishi', 'model' => 'Pajero Sport'],
    ['id' => 146, 'merk' => 'Mitsubishi', 'model' => 'Outlander Sport'],
    ['id' => 147, 'merk' => 'Mitsubishi', 'model' => 'L300'],
    ['id' => 148, 'merk' => 'Mitsubishi', 'model' => 'Colt Diesel'],
    ['id' => 149, 'merk' => 'Mitsubishi', 'model' => 'Triton'],
    ['id' => 150, 'merk' => 'Mitsubishi', 'model' => 'Mirage'],
    ['id' => 151, 'merk' => 'Mitsubishi', 'model' => 'Eclipse Cross'],
    ['id' => 152, 'merk' => 'Hyundai', 'model' => 'Avega'],
    ['id' => 153, 'merk' => 'Hyundai', 'model' => 'i10'],
    ['id' => 154, 'merk' => 'Hyundai', 'model' => 'i20'],
    ['id' => 155, 'merk' => 'Hyundai', 'model' => 'Accent'],
    ['id' => 156, 'merk' => 'Hyundai', 'model' => 'Elantra'],
    ['id' => 157, 'merk' => 'Hyundai', 'model' => 'Sonata'],
    ['id' => 158, 'merk' => 'Hyundai', 'model' => 'Tucson'],
    ['id' => 159, 'merk' => 'Hyundai', 'model' => 'Santa Fe'],
    ['id' => 160, 'merk' => 'Hyundai', 'model' => 'Stargazer'],
    ['id' => 161, 'merk' => 'Hyundai', 'model' => 'Creta'],
    ['id' => 162, 'merk' => 'Hyundai', 'model' => 'Palisade'],
    ['id' => 163, 'merk' => 'Hyundai', 'model' => 'Ioniq 5'],
    ['id' => 164, 'merk' => 'Hyundai', 'model' => 'Kona Electric'],
    ['id' => 165, 'merk' => 'Kia', 'model' => 'Picanto'],
    ['id' => 166, 'merk' => 'Kia', 'model' => 'Rio'],
    ['id' => 167, 'merk' => 'Kia', 'model' => 'Seltos'],
    ['id' => 168, 'merk' => 'Kia', 'model' => 'Sonet'],
    ['id' => 169, 'merk' => 'Kia', 'model' => 'Sportage'],
    ['id' => 170, 'merk' => 'Kia', 'model' => 'Sorento'],
    ['id' => 171, 'merk' => 'Kia', 'model' => 'Carens'],
    ['id' => 172, 'merk' => 'Kia', 'model' => 'Carnival'],
    ['id' => 173, 'merk' => 'Kia', 'model' => 'Pregio'],
    ['id' => 174, 'merk' => 'Kia', 'model' => 'Optima'],
    ['id' => 175, 'merk' => 'Kia', 'model' => 'Cerato'],
    ['id' => 176, 'merk' => 'Kia', 'model' => 'Stinger'],
    ['id' => 177, 'merk' => 'Kia', 'model' => 'EV6'],
    ['id' => 178, 'merk' => 'BMW', 'model' => '2 Series'],
    ['id' => 179, 'merk' => 'BMW', 'model' => '3 Series'],
    ['id' => 180, 'merk' => 'BMW', 'model' => '4 Series'],
    ['id' => 181, 'merk' => 'BMW', 'model' => '5 Series'],
    ['id' => 182, 'merk' => 'BMW', 'model' => '7 Series'],
    ['id' => 183, 'merk' => 'BMW', 'model' => 'X1'],
    ['id' => 184, 'merk' => 'BMW', 'model' => 'X3'],
    ['id' => 185, 'merk' => 'BMW', 'model' => 'X5'],
    ['id' => 186, 'merk' => 'BMW', 'model' => 'X6'],
    ['id' => 187, 'merk' => 'BMW', 'model' => 'X7'],
    ['id' => 188, 'merk' => 'BMW', 'model' => 'Z4'],
    ['id' => 189, 'merk' => 'Mercedes-Benz', 'model' => 'A-Class'],
    ['id' => 190, 'merk' => 'Mercedes-Benz', 'model' => 'B-Class'],
    ['id' => 191, 'merk' => 'Mercedes-Benz', 'model' => 'C-Class'],
    ['id' => 192, 'merk' => 'Mercedes-Benz', 'model' => 'E-Class'],
    ['id' => 193, 'merk' => 'Mercedes-Benz', 'model' => 'S-Class'],
    ['id' => 194, 'merk' => 'Mercedes-Benz', 'model' => 'CLA'],
    ['id' => 195, 'merk' => 'Mercedes-Benz', 'model' => 'GLA'],
    ['id' => 196, 'merk' => 'Mercedes-Benz', 'model' => 'GLB'],
    ['id' => 197, 'merk' => 'Mercedes-Benz', 'model' => 'GLC'],
    ['id' => 198, 'merk' => 'Mercedes-Benz', 'model' => 'GLE'],
    ['id' => 199, 'merk' => 'Mercedes-Benz', 'model' => 'GLS'],
    ['id' => 200, 'merk' => 'Mercedes-Benz', 'model' => 'G-Class'],
    ['id' => 201, 'merk' => 'Audi', 'model' => 'A1'],
    ['id' => 202, 'merk' => 'Audi', 'model' => 'A3'],
    ['id' => 203, 'merk' => 'Audi', 'model' => 'A4'],
    ['id' => 204, 'merk' => 'Audi', 'model' => 'A5'],
    ['id' => 205, 'merk' => 'Audi', 'model' => 'A6'],
    ['id' => 206, 'merk' => 'Audi', 'model' => 'A7'],
    ['id' => 207, 'merk' => 'Audi', 'model' => 'A8'],
    ['id' => 208, 'merk' => 'Audi', 'model' => 'Q2'],
    ['id' => 209, 'merk' => 'Audi', 'model' => 'Q3'],
    ['id' => 210, 'merk' => 'Audi', 'model' => 'Q5'],
    ['id' => 211, 'merk' => 'Audi', 'model' => 'Q7'],
    ['id' => 212, 'merk' => 'Audi', 'model' => 'Q8'],
    ['id' => 213, 'merk' => 'Audi', 'model' => 'TT'],

    ['id' => 214, 'merk' => 'Volvo', 'model' => 'S60'],
    ['id' => 215, 'merk' => 'Volvo', 'model' => 'S90'],
    ['id' => 216, 'merk' => 'Volvo', 'model' => 'XC40'],
    ['id' => 217, 'merk' => 'Volvo', 'model' => 'XC60'],
    ['id' => 218, 'merk' => 'Volvo', 'model' => 'XC90'],
    ['id' => 219, 'merk' => 'Volvo', 'model' => 'V40'],
    ['id' => 220, 'merk' => 'Volvo', 'model' => 'V60'],

    ['id' => 221, 'merk' => 'Mini', 'model' => 'Cooper'],
    ['id' => 222, 'merk' => 'Mini', 'model' => 'Cooper 3 Door'],
    ['id' => 223, 'merk' => 'Mini', 'model' => 'Cooper 5 Door'],
    ['id' => 224, 'merk' => 'Mini', 'model' => 'Countryman'],
    ['id' => 225, 'merk' => 'Mini', 'model' => 'Clubman'],
    ['id' => 226, 'merk' => 'Mini', 'model' => 'Convertible'],

    ['id' => 227, 'merk' => 'Peugeot', 'model' => '208'],
    ['id' => 228, 'merk' => 'Peugeot', 'model' => '2008'],
    ['id' => 229, 'merk' => 'Peugeot', 'model' => '3008'],
    ['id' => 230, 'merk' => 'Peugeot', 'model' => '5008'],
    ['id' => 231, 'merk' => 'Peugeot', 'model' => 'Partner'],

    ['id' => 232, 'merk' => 'Citroën', 'model' => 'C3'],
    ['id' => 233, 'merk' => 'Citroën', 'model' => 'C3 Aircross'],
    ['id' => 234, 'merk' => 'Citroën', 'model' => 'C5 Aircross'],
    ['id' => 235, 'merk' => 'Citroën', 'model' => 'Berlingo'],

    ['id' => 236, 'merk' => 'Renault', 'model' => 'Kwid'],
    ['id' => 237, 'merk' => 'Renault', 'model' => 'Duster'],
    ['id' => 238, 'merk' => 'Renault', 'model' => 'Triber'],
    ['id' => 239, 'merk' => 'Renault', 'model' => 'Captur'],
    ['id' => 240, 'merk' => 'Renault', 'model' => 'Koleos'],

    ['id' => 241, 'merk' => 'Chevrolet', 'model' => 'Spark'],
    ['id' => 242, 'merk' => 'Chevrolet', 'model' => 'Aveo'],
    ['id' => 243, 'merk' => 'Chevrolet', 'model' => 'Optra'],
    ['id' => 244, 'merk' => 'Chevrolet', 'model' => 'Cruze'],
    ['id' => 245, 'merk' => 'Chevrolet', 'model' => 'Captiva'],
    ['id' => 246, 'merk' => 'Chevrolet', 'model' => 'Trailblazer'],
    ['id' => 247, 'merk' => 'Chevrolet', 'model' => 'Colorado'],

    ['id' => 248, 'merk' => 'Jeep', 'model' => 'Wrangler'],
    ['id' => 249, 'merk' => 'Jeep', 'model' => 'Wrangler Unlimited'],
    ['id' => 250, 'merk' => 'Jeep', 'model' => 'Grand Cherokee'],
    ['id' => 251, 'merk' => 'Jeep', 'model' => 'Cherokee'],
    ['id' => 252, 'merk' => 'Jeep', 'model' => 'Compass'],

    ['id' => 253, 'merk' => 'Ford', 'model' => 'Fiesta'],
    ['id' => 254, 'merk' => 'Ford', 'model' => 'Focus'],
    ['id' => 255, 'merk' => 'Ford', 'model' => 'EcoSport'],
    ['id' => 256, 'merk' => 'Ford', 'model' => 'Escape'],
    ['id' => 257, 'merk' => 'Ford', 'model' => 'Explorer'],
    ['id' => 258, 'merk' => 'Ford', 'model' => 'Everest'],
    ['id' => 259, 'merk' => 'Ford', 'model' => 'Ranger'],
    ['id' => 260, 'merk' => 'Ford', 'model' => 'Raptor'],

    ['id' => 261, 'merk' => 'Wuling', 'model' => 'Confero'],
    ['id' => 262, 'merk' => 'Wuling', 'model' => 'Cortez'],
    ['id' => 263, 'merk' => 'Wuling', 'model' => 'Almaz'],
    ['id' => 264, 'merk' => 'Wuling', 'model' => 'Alvez'],
    ['id' => 265, 'merk' => 'Wuling', 'model' => 'Air EV'],
    ['id' => 266, 'merk' => 'Wuling', 'model' => 'Formo'],

    ['id' => 267, 'merk' => 'DFSK', 'model' => 'Glory 580'],
    ['id' => 268, 'merk' => 'DFSK', 'model' => 'Glory 560'],
    ['id' => 269, 'merk' => 'DFSK', 'model' => 'Gelora'],
    ['id' => 270, 'merk' => 'DFSK', 'model' => 'Super Cab'],
    ['id' => 271, 'merk' => 'DFSK', 'model' => 'Seres E1'],

    ['id' => 272, 'merk' => 'BYD', 'model' => 'Atto 3'],
    ['id' => 273, 'merk' => 'BYD', 'model' => 'Dolphin'],
    ['id' => 274, 'merk' => 'BYD', 'model' => 'Seal'],
    ['id' => 275, 'merk' => 'BYD', 'model' => 'M6'],

    ['id' => 276, 'merk' => 'Chery', 'model' => 'Tiggo 5X'],
    ['id' => 277, 'merk' => 'Chery', 'model' => 'Tiggo 7 Pro'],
    ['id' => 278, 'merk' => 'Chery', 'model' => 'Tiggo 8 Pro'],
    ['id' => 279, 'merk' => 'Chery', 'model' => 'Omoda 5'],
    ['id' => 280, 'merk' => 'Chery', 'model' => 'J6'],
    ['id' => 281, 'merk' => 'Chery', 'model' => 'E5'],

    ['id' => 282, 'merk' => 'Haval', 'model' => 'Haval H6'],
    ['id' => 283, 'merk' => 'Haval', 'model' => 'Haval Jolion'],

    ['id' => 284, 'merk' => 'Great Wall', 'model' => 'Wingle 5'],
    ['id' => 285, 'merk' => 'Great Wall', 'model' => 'Wingle 7'],

    ['id' => 286, 'merk' => 'MG', 'model' => 'ZS'],
    ['id' => 287, 'merk' => 'MG', 'model' => 'HS'],
    ['id' => 288, 'merk' => 'MG', 'model' => '5 EV'],
    ['id' => 289, 'merk' => 'MG', 'model' => '4 EV'],
    ['id' => 290, 'merk' => 'MG', 'model' => 'Marvel R'],

    ['id' => 291, 'merk' => 'BAIC', 'model' => 'BJ40'],
    ['id' => 292, 'merk' => 'BAIC', 'model' => 'X55'],
    ['id' => 293, 'merk' => 'BAIC', 'model' => 'EU5'],

    ['id' => 294, 'merk' => 'Jetour', 'model' => 'Dashing'],
    ['id' => 295, 'merk' => 'Jetour', 'model' => 'X70'],
    ['id' => 296, 'merk' => 'Jetour', 'model' => 'X90'],

    ['id' => 297, 'merk' => 'Neta', 'model' => 'V'],
    ['id' => 298, 'merk' => 'Neta', 'model' => 'U'],

    ['id' => 299, 'merk' => 'Aion', 'model' => 'Y'],
    ['id' => 300, 'merk' => 'Aion', 'model' => 'ES'],
    ['id' => 301, 'merk' => 'Aion', 'model' => 'V'],

    ['id' => 302, 'merk' => 'Geely', 'model' => 'Emgrand'],
    ['id' => 303, 'merk' => 'Geely', 'model' => 'Coolray'],

    ['id' => 304, 'merk' => 'Changan', 'model' => 'CS35 Plus'],
    ['id' => 305, 'merk' => 'Changan', 'model' => 'Alsvin'],

        ]);
    }
}