<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InspeksiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('inspeksi')->insert([
            [
                'id' => 1,
                'mobil_id' => 1,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'B',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'A',
                'catatan' => null,
                'tanggal_inspeksi' => '2025-12-10',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 2,
                'mobil_id' => 2,
                'staff_id' => 9,
                'grade_eksterior' => 'B',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'A',
                'catatan' => null,
                'tanggal_inspeksi' => '2025-12-11',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 3,
                'mobil_id' => 3,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'A',
                'grade_mesin' => 'B',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2025-11-01',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 4,
                'mobil_id' => 4,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'B',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2025-10-01',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 5,
                'mobil_id' => 5,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'A',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-01-10',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 6,
                'mobil_id' => 6,
                'staff_id' => 9,
                'grade_eksterior' => 'B',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-01-11',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 7,
                'mobil_id' => 7,
                'staff_id' => 9,
                'grade_eksterior' => 'A',
                'grade_interior' => 'B',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-03-05',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 8,
                'mobil_id' => 8,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'A',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-04-01',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 9,
                'mobil_id' => 9,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'A',
                'grade_mesin' => 'B',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-04-02',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 10,
                'mobil_id' => 10,
                'staff_id' => 3,
                'grade_eksterior' => 'A',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'A',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-04-03',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
            [
                'id' => 11,
                'mobil_id' => 11,
                'staff_id' => 3,
                'grade_eksterior' => 'B',
                'grade_interior' => 'A',
                'grade_mesin' => 'A',
                'grade_kelengkapan' => 'A',
                'grade_keseluruhan' => 'B',
                'catatan' => null,
                'tanggal_inspeksi' => '2026-04-04',
                'created_at' => '2026-05-28 22:18:39',
                'updated_at' => '2026-05-28 22:18:39',
            ],
        ]);
    }
}