<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InspeksiMesinSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('inspeksi_mesin')->insert([
            [
                'id' => 1,
                'inspeksi_id' => 1,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 2,
                'inspeksi_id' => 2,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 3,
                'inspeksi_id' => 3,
                'suara_mesin' => 'B',
                'foto_suara_mesin' => null,
                'note_suara_mesin' => 'ada baret tipis',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 4,
                'inspeksi_id' => 4,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 5,
                'inspeksi_id' => 5,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 6,
                'inspeksi_id' => 6,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 7,
                'inspeksi_id' => 7,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 8,
                'inspeksi_id' => 8,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 9,
                'inspeksi_id' => 9,
                'suara_mesin' => 'B',
                'foto_suara_mesin' => null,
                'note_suara_mesin' => 'ada baret tipis',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 10,
                'inspeksi_id' => 10,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
            [
                'id' => 11,
                'inspeksi_id' => 11,
                'suara_mesin' => 'A',
                'getaran_mesin' => 'A',
                'kebocoran_oli' => 'A',
                'asap_knalpot' => 'A',
                'transmisi' => 'A',
                'rem' => 'A',
                'power_steering' => 'A',
                'suspensi' => 'A',
                'radiator' => 'A',
                'aki' => 'A',
                'indikator_dashboard' => 'A',
            ],
        ]);
    }
}