<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InspeksiEksteriorSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('inspeksi_eksterior')->insert([
            [
                'id' => 1,
                'inspeksi_id' => 1,
                'kondisi_cat' => 'B',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => 'ada baret tipis',
                'panel_bodi' => 'A',
                'foto_panel_bodi' => null,
                'note_panel_bodi' => null,
                'lampu_depan' => 'A',
                'foto_lampu_depan' => null,
                'note_lampu_depan' => null,
                'lampu_belakang' => 'A',
                'foto_lampu_belakang' => null,
                'note_lampu_belakang' => null,
                'velg' => 'A',
                'foto_velg' => null,
                'note_velg' => null,
                'ban' => 'A',
                'foto_ban' => null,
                'note_ban' => null,
                'kaca' => 'A',
                'foto_kaca' => null,
                'note_kaca' => null,
                'wiper' => 'A',
                'foto_wiper' => null,
                'note_wiper' => null,
            ],
            [
                'id' => 2,
                'inspeksi_id' => 2,
                'kondisi_cat' => 'A',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => null,
                'panel_bodi' => 'B',
                'foto_panel_bodi' => null,
                'note_panel_bodi' => 'ada baret tipis',
                'lampu_depan' => 'A',
                'foto_lampu_depan' => null,
                'note_lampu_depan' => null,
                'lampu_belakang' => 'A',
                'foto_lampu_belakang' => null,
                'note_lampu_belakang' => null,
                'velg' => 'A',
                'foto_velg' => null,
                'note_velg' => null,
                'ban' => 'A',
                'foto_ban' => null,
                'note_ban' => null,
                'kaca' => 'A',
                'foto_kaca' => null,
                'note_kaca' => null,
                'wiper' => 'A',
                'foto_wiper' => null,
                'note_wiper' => null,
            ],
            [
                'id' => 3,
                'inspeksi_id' => 3,
                'kondisi_cat' => 'A',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => null,
                'panel_bodi' => 'A',
                'foto_panel_bodi' => null,
                'note_panel_bodi' => null,
                'lampu_depan' => 'A',
                'foto_lampu_depan' => null,
                'note_lampu_depan' => null,
                'lampu_belakang' => 'A',
                'foto_lampu_belakang' => null,
                'note_lampu_belakang' => null,
                'velg' => 'A',
                'foto_velg' => null,
                'note_velg' => null,
                'ban' => 'A',
                'foto_ban' => null,
                'note_ban' => null,
                'kaca' => 'A',
                'foto_kaca' => null,
                'note_kaca' => null,
                'wiper' => 'A',
                'foto_wiper' => null,
                'note_wiper' => null,
            ],
            [
                'id' => 4,
                'inspeksi_id' => 4,
                'kondisi_cat' => 'B',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => 'ada baret tipis',
                'panel_bodi' => 'A',
                'foto_panel_bodi' => null,
                'note_panel_bodi' => null,
                'lampu_depan' => 'A',
                'foto_lampu_depan' => null,
                'note_lampu_depan' => null,
                'lampu_belakang' => 'A',
                'foto_lampu_belakang' => null,
                'note_lampu_belakang' => null,
                'velg' => 'A',
                'foto_velg' => null,
                'note_velg' => null,
                'ban' => 'A',
                'foto_ban' => null,
                'note_ban' => null,
                'kaca' => 'A',
                'foto_kaca' => null,
                'note_kaca' => null,
                'wiper' => 'A',
                'foto_wiper' => null,
                'note_wiper' => null,
            ],
            [
                'id' => 5,
                'inspeksi_id' => 5,
                'kondisi_cat' => 'A',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => null,
                'panel_bodi' => 'A',
                'foto_panel_bodi' => null,
                'note_panel_bodi' => null,
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 6,
                'inspeksi_id' => 6,
                'kondisi_cat' => 'B',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => 'ada baret tipis',
                'panel_bodi' => 'A',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 7,
                'inspeksi_id' => 7,
                'kondisi_cat' => 'A',
                'panel_bodi' => 'B',
                'note_panel_bodi' => 'ada baret tipis',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 8,
                'inspeksi_id' => 8,
                'kondisi_cat' => 'A',
                'panel_bodi' => 'A',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 9,
                'inspeksi_id' => 9,
                'kondisi_cat' => 'A',
                'foto_kondisi_cat' => 'eksterior/wasd.jpg',
                'panel_bodi' => 'A',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 10,
                'inspeksi_id' => 10,
                'kondisi_cat' => 'A',
                'panel_bodi' => 'A',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ],
            [
                'id' => 11,
                'inspeksi_id' => 11,
                'kondisi_cat' => 'B',
                'foto_kondisi_cat' => null,
                'note_kondisi_cat' => 'ada baret tipis',
                'panel_bodi' => 'A',
                'lampu_depan' => 'A',
                'lampu_belakang' => 'A',
                'velg' => 'A',
                'ban' => 'A',
                'kaca' => 'A',
                'wiper' => 'A',
            ]
        ]);
    }
}