<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InspeksiInteriorSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('inspeksi_interior')->insert([
            [
                'id' => 1,
                'inspeksi_id' => 1,
                'kebersihan_kabin' => 'A',
                'foto_kebersihan_kabin' => null,
                'note_kebersihan_kabin' => null,
                'kondisi_jok' => 'B',
                'foto_kondisi_jok' => null,
                'note_kondisi_jok' => 'ada baret tipis',
                'dashboard' => 'A',
                'foto_dashboard' => null,
                'note_dashboard' => null,
                'audio' => 'A',
                'foto_audio' => null,
                'note_audio' => null,
                'ac' => 'A',
                'foto_ac' => null,
                'note_ac' => null,
                'speedometer' => 'A',
                'foto_speedometer' => null,
                'note_speedometer' => null,
                'karpet' => 'A',
                'foto_karpet' => null,
                'note_karpet' => null,
                'power_window' => 'A',
                'foto_power_window' => null,
                'note_power_window' => null,
                'sunroof' => 'A',
                'foto_sunroof' => null,
                'note_sunroof' => null,
                'sabuk_pengaman' => 'A',
                'foto_sabuk_pengaman' => null,
                'note_sabuk_pengaman' => null,
                'setir_transmisi' => 'A',
                'foto_setir_transmisi' => null,
                'note_setir_transmisi' => null,
            ],
            [
                'id' => 2,
                'inspeksi_id' => 2,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 3,
                'inspeksi_id' => 3,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 4,
                'inspeksi_id' => 4,
                'kebersihan_kabin' => 'B',
                'foto_kebersihan_kabin' => null,
                'note_kebersihan_kabin' => 'ada baret tipis',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 5,
                'inspeksi_id' => 5,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 6,
                'inspeksi_id' => 6,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 7,
                'inspeksi_id' => 7,
                'kebersihan_kabin' => 'B',
                'foto_kebersihan_kabin' => null,
                'note_kebersihan_kabin' => 'ada baret tipis',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 8,
                'inspeksi_id' => 8,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 9,
                'inspeksi_id' => 9,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 10,
                'inspeksi_id' => 10,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
            [
                'id' => 11,
                'inspeksi_id' => 11,
                'kebersihan_kabin' => 'A',
                'kondisi_jok' => 'A',
                'dashboard' => 'A',
                'audio' => 'A',
                'ac' => 'A',
                'speedometer' => 'A',
                'karpet' => 'A',
                'power_window' => 'A',
                'sunroof' => 'A',
                'sabuk_pengaman' => 'A',
                'setir_transmisi' => 'A',
            ],
        ]);
    }
}