<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalInspeksiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('jadwal_inspeksi')->insert([
            [
                'id'=>1,
                'order_id'=>'INSPEKSI-1',
                'user_id'=>1,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Wuling',
                'model_mobil'=>'Cortez',
                'tahun'=>2020,
                'transmisi'=>'Automatic',
                'warna'=>'Putih',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0811111111',
                'alamat'=>'Surabaya',
                'kecamatan'=>'Sukolilo',
                'jadwal'=>'2025-12-10',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2025-12-10 00:00:00',
                'updated_at'=>'2025-12-10 00:00:00',
                'kilometer'=>45000,
                'mobil_id'=>1,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>2,
                'order_id'=>'INSPEKSI-2',
                'user_id'=>8,
                'staff_id'=>9,
                'status'=>3,
                'merk'=>'Hyundai',
                'model_mobil'=>'Santafe',
                'tahun'=>2021,
                'transmisi'=>'Automatic',
                'warna'=>'Hitam',
                'tipe_mesin'=>'Diesel',
                'nomor_kontak'=>'0822222222',
                'alamat'=>'Sidoarjo',
                'kecamatan'=>'Buduran',
                'jadwal'=>'2025-12-11',
                'jam'=>'11:00:00',
                'note'=>null,
                'created_at'=>'2025-12-11 00:00:00',
                'updated_at'=>'2025-12-11 00:00:00',
                'kilometer'=>35000,
                'mobil_id'=>2,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>3,
                'order_id'=>'INSPEKSI-3',
                'user_id'=>11,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Kia',
                'model_mobil'=>'Sorento',
                'tahun'=>2019,
                'transmisi'=>'Automatic',
                'warna'=>'Silver',
                'tipe_mesin'=>'Diesel',
                'nomor_kontak'=>'0833333333',
                'alamat'=>'Gresik',
                'kecamatan'=>'Manyar',
                'jadwal'=>'2025-11-01',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2025-11-01 00:00:00',
                'updated_at'=>'2025-11-01 00:00:00',
                'kilometer'=>60000,
                'mobil_id'=>3,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>4,
                'order_id'=>'INSPEKSI-4',
                'user_id'=>12,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Mitsubishi',
                'model_mobil'=>'Xpander',
                'tahun'=>2022,
                'transmisi'=>'Manual',
                'warna'=>'Putih',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0844444444',
                'alamat'=>'Surabaya',
                'kecamatan'=>'Rungkut',
                'jadwal'=>'2025-10-01',
                'jam'=>'11:00:00',
                'note'=>null,
                'created_at'=>'2025-10-01 00:00:00',
                'updated_at'=>'2025-10-01 00:00:00',
                'kilometer'=>25000,
                'mobil_id'=>4,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>5,
                'order_id'=>'INSPEKSI-5',
                'user_id'=>13,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Toyota',
                'model_mobil'=>'Yaris',
                'tahun'=>2021,
                'transmisi'=>'Automatic',
                'warna'=>'Merah',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0855555555',
                'alamat'=>'Malang',
                'kecamatan'=>'Lowokwaru',
                'jadwal'=>'2026-01-10',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2026-01-10 00:00:00',
                'updated_at'=>'2026-01-10 00:00:00',
                'kilometer'=>30000,
                'mobil_id'=>5,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>6,
                'order_id'=>'INSPEKSI-6',
                'user_id'=>1,
                'staff_id'=>9,
                'status'=>3,
                'merk'=>'BMW',
                'model_mobil'=>'X1',
                'tahun'=>2020,
                'transmisi'=>'Automatic',
                'warna'=>'Putih',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0811111111',
                'alamat'=>'Surabaya',
                'kecamatan'=>'Wonokromo',
                'jadwal'=>'2026-01-11',
                'jam'=>'11:00:00',
                'note'=>null,
                'created_at'=>'2026-01-11 00:00:00',
                'updated_at'=>'2026-01-11 00:00:00',
                'kilometer'=>40000,
                'mobil_id'=>6,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>7,
                'order_id'=>'INSPEKSI-7',
                'user_id'=>8,
                'staff_id'=>9,
                'status'=>3,
                'merk'=>'Mini Cooper',
                'model_mobil'=>'Mini',
                'tahun'=>2018,
                'transmisi'=>'Automatic',
                'warna'=>'Kuning',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0822222222',
                'alamat'=>'Sidoarjo',
                'kecamatan'=>'Taman',
                'jadwal'=>'2026-03-05',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2026-03-05 00:00:00',
                'updated_at'=>'2026-03-05 00:00:00',
                'kilometer'=>50000,
                'mobil_id'=>7,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>8,
                'order_id'=>'INSPEKSI-8',
                'user_id'=>11,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Toyota',
                'model_mobil'=>'Avanza',
                'tahun'=>2022,
                'transmisi'=>'Manual',
                'warna'=>'Hitam',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0833333333',
                'alamat'=>'Gresik',
                'kecamatan'=>'Kebomas',
                'jadwal'=>'2026-04-01',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2026-04-01 00:00:00',
                'updated_at'=>'2026-04-01 00:00:00',
                'kilometer'=>20000,
                'mobil_id'=>8,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>9,
                'order_id'=>'INSPEKSI-9',
                'user_id'=>12,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Honda',
                'model_mobil'=>'Civic',
                'tahun'=>2020,
                'transmisi'=>'Automatic',
                'warna'=>'Putih',
                'tipe_mesin'=>'Bensin',
                'nomor_kontak'=>'0844444444',
                'alamat'=>'Surabaya',
                'kecamatan'=>'Gayungan',
                'jadwal'=>'2026-04-02',
                'jam'=>'11:00:00',
                'note'=>null,
                'created_at'=>'2026-04-02 00:00:00',
                'updated_at'=>'2026-04-02 00:00:00',
                'kilometer'=>45000,
                'mobil_id'=>9,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>10,
                'order_id'=>'INSPEKSI-10',
                'user_id'=>13,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Toyota',
                'model_mobil'=>'Fortuner',
                'tahun'=>2021,
                'transmisi'=>'Automatic',
                'warna'=>'Hitam',
                'tipe_mesin'=>'Diesel',
                'nomor_kontak'=>'0855555555',
                'alamat'=>'Malang',
                'kecamatan'=>'Blimbing',
                'jadwal'=>'2026-04-03',
                'jam'=>'14:00:00',
                'note'=>null,
                'created_at'=>'2026-04-03 00:00:00',
                'updated_at'=>'2026-04-03 00:00:00',
                'kilometer'=>38000,
                'mobil_id'=>10,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>11,
                'order_id'=>'INSPEKSI-11',
                'user_id'=>1,
                'staff_id'=>3,
                'status'=>3,
                'merk'=>'Mitsubishi',
                'model_mobil'=>'Pajero',
                'tahun'=>2019,
                'transmisi'=>'Automatic',
                'warna'=>'Silver',
                'tipe_mesin'=>'Diesel',
                'nomor_kontak'=>'0811111111',
                'alamat'=>'Surabaya',
                'kecamatan'=>'Lakarsantri',
                'jadwal'=>'2026-04-04',
                'jam'=>'08:00:00',
                'note'=>null,
                'created_at'=>'2026-04-04 00:00:00',
                'updated_at'=>'2026-04-04 00:00:00',
                'kilometer'=>55000,
                'mobil_id'=>11,
                'tipe'=>'inspeksi'
            ],
            [
                'id'=>140,
                'order_id'=>'INSPEKSI-140-6a1d313e33b36',
                'user_id'=>14,
                'staff_id'=>3,
                'status'=>2,
                'merk'=>'Mitsubishi',
                'model_mobil'=>'Pajero',
                'tahun'=>2013,
                'transmisi'=>'Automatic',
                'warna'=>'putih',
                'tipe_mesin'=>'Diesel',
                'nomor_kontak'=>'0898767897652',
                'alamat'=>'Pucang Rinenggo No.5',
                'kecamatan'=>'Barat',
                'jadwal'=>'2026-06-04',
                'jam'=>'11:00:00',
                'note'=>null,
                'created_at'=>'2026-06-01 07:14:06',
                'updated_at'=>'2026-06-01 07:15:39',
                'kilometer'=>224345,
                'mobil_id'=>null,
                'tipe'=>'inspeksi'
            ]
        ]);
    }
}