<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalBookingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('jadwal_booking')->insert([
            [
                'id' => 1,
                'mobil_id' => 1,
                'order_id' => 'BOOKING-1-AAA111',
                'user_id' => 8,
                'pembeli_id' => 8,
                'staff_id' => 3,
                'status' => 3,
                'merk' => 'Wuling',
                'model_mobil' => 'Cortez',
                'tahun' => 2022,
                'transmisi' => 'Automatic',
                'warna' => 'Putih',
                'tipe_mesin' => 'Bensin',
                'nomor_kontak' => '081111111111',
                'alamat_asal' => 'Sidoarjo',
                'kecamatan_asal' => 'Buduran',
                'alamat_tujuan' => 'Surabaya',
                'kecamatan_tujuan' => 'Wonokromo',
                'jadwal' => '2026-01-18',
                'jam' => '08:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 25000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 2,
                'mobil_id' => 2,
                'order_id' => 'BOOKING-2-BBB222',
                'user_id' => 11,
                'pembeli_id' => 11,
                'staff_id' => 9,
                'status' => 3,
                'merk' => 'Hyundai',
                'model_mobil' => 'Santafe',
                'tahun' => 2021,
                'transmisi' => 'Automatic',
                'warna' => 'Hitam',
                'tipe_mesin' => 'Diesel',
                'nomor_kontak' => '082222222222',
                'alamat_asal' => 'Surabaya',
                'kecamatan_asal' => 'Tegalsari',
                'alamat_tujuan' => 'Sidoarjo',
                'kecamatan_tujuan' => 'Candi',
                'jadwal' => '2026-01-23',
                'jam' => '11:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 40000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 3,
                'mobil_id' => 3,
                'order_id' => 'BOOKING-3-CCC333',
                'user_id' => 12,
                'pembeli_id' => 12,
                'staff_id' => 3,
                'status' => 3,
                'merk' => 'Kia',
                'model_mobil' => 'Sorento',
                'tahun' => 2020,
                'transmisi' => 'Automatic',
                'warna' => 'Abu Abu',
                'tipe_mesin' => 'Diesel',
                'nomor_kontak' => '083333333333',
                'alamat_asal' => 'Malang',
                'kecamatan_asal' => 'Lowokwaru',
                'alamat_tujuan' => 'Surabaya',
                'kecamatan_tujuan' => 'Sukolilo',
                'jadwal' => '2025-12-26',
                'jam' => '14:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 35000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 4,
                'mobil_id' => 4,
                'order_id' => 'BOOKING-4-DDD444',
                'user_id' => 13,
                'pembeli_id' => 13,
                'staff_id' => 9,
                'status' => 3,
                'merk' => 'Mitsubishi',
                'model_mobil' => 'Xpander',
                'tahun' => 2021,
                'transmisi' => 'Manual',
                'warna' => 'Silver',
                'tipe_mesin' => 'Bensin',
                'nomor_kontak' => '084444444444',
                'alamat_asal' => 'Sidoarjo',
                'kecamatan_asal' => 'Krian',
                'alamat_tujuan' => 'Gresik',
                'kecamatan_tujuan' => 'Manyar',
                'jadwal' => '2025-11-16',
                'jam' => '08:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 30000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 5,
                'mobil_id' => 5,
                'order_id' => 'BOOKING-5-EEE555',
                'user_id' => 1,
                'pembeli_id' => 1,
                'staff_id' => 3,
                'status' => 3,
                'merk' => 'Toyota',
                'model_mobil' => 'Yaris',
                'tahun' => 2022,
                'transmisi' => 'Automatic',
                'warna' => 'Merah',
                'tipe_mesin' => 'Bensin',
                'nomor_kontak' => '085555555555',
                'alamat_asal' => 'Surabaya',
                'kecamatan_asal' => 'Rungkut',
                'alamat_tujuan' => 'Sidoarjo',
                'kecamatan_tujuan' => 'Taman',
                'jadwal' => '2026-02-13',
                'jam' => '11:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 20000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 6,
                'mobil_id' => 6,
                'order_id' => 'BOOKING-6-FFF666',
                'user_id' => 8,
                'pembeli_id' => 8,
                'staff_id' => 9,
                'status' => 3,
                'merk' => 'BMW',
                'model_mobil' => 'X1',
                'tahun' => 2023,
                'transmisi' => 'Automatic',
                'warna' => 'Putih',
                'tipe_mesin' => 'Bensin',
                'nomor_kontak' => '086666666666',
                'alamat_asal' => 'Sidoarjo',
                'kecamatan_asal' => 'Waru',
                'alamat_tujuan' => 'Surabaya',
                'kecamatan_tujuan' => 'Gayungan',
                'jadwal' => '2026-02-20',
                'jam' => '14:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 15000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
            [
                'id' => 7,
                'mobil_id' => 7,
                'order_id' => 'BOOKING-7-GGG777',
                'user_id' => 11,
                'pembeli_id' => 11,
                'staff_id' => 3,
                'status' => 3,
                'merk' => 'Mini Cooper',
                'model_mobil' => 'Mini',
                'tahun' => 2021,
                'transmisi' => 'Automatic',
                'warna' => 'Kuning',
                'tipe_mesin' => 'Bensin',
                'nomor_kontak' => '087777777777',
                'alamat_asal' => 'Surabaya',
                'kecamatan_asal' => 'Gubeng',
                'alamat_tujuan' => 'Sidoarjo',
                'kecamatan_tujuan' => 'Porong',
                'jadwal' => '2026-04-10',
                'jam' => '08:00:00',
                'note' => 'Mobil berhasil dikirim',
                'kilometer' => 18000,
                'created_at' => '2026-05-28 22:26:37',
                'updated_at' => '2026-05-28 22:26:37',
            ],
        ]);
    }
}